package day18;

import java.util.Scanner;

public class Execeptions {

	public static void main(String[] args) 
	{
		System.out.println("programe is started");
		Scanner sc=new Scanner(System.in);
		System.out.println("enter a num");
		int num=sc.nextInt();
		System.out.println(100/num);
		
		System.out.println("programe is completed"); 
		
		System.out.println("programe is exited");
		
		/*

		int arry[]=new int[5];
		System.out.println("enter teh position");
		int pos= sc.nextInt();
		System.out.println("enter the value");
		int val=sc.nextInt();
		System.out.println("programe completed");
		System.out.println("programe exited");
		*/  
		
		//String to integer
	/*	
		String s="1100";
		int num =Integer.parseInt(s);
		System.out.println (num);
	*/	
	/*	String s="welcome";
		System.out.println(s.length());
		System.out.println("programe completed");
		System.out.println("programe exited");  */
	}

}
